// internal/cluster/registry.go
//
// Registry is the coordinator's authoritative view of all worker nodes.
//
// v1 bug fixes implemented here
// ──────────────────────────────
// CheckHealth() deadlock: eliminated by design. The coordinator never contacts
// nodes. Nodes push heartbeats in via the gRPC Heartbeat bidi-stream. Health
// is derived purely from the recency of the last heartbeat received.
//
// Concurrency model
// ─────────────────
// mu (RWMutex) protects the nodes map pointer:
//   - mu.Lock()  for: Register (new entry), Restore.
//   - mu.RLock() for: Snapshot, HealthyNodes, Lookup, Len.
//   - No lock for: updating _lastSeen / _running atomics on an existing
//     *nodeEntry — the pointer is stable once inserted; atomics self-synchronise.
//
// HandleHeartbeat is effectively lock-free for existing nodes:
//   1. RLock → look up pointer → RUnlock.
//   2. atomic.Store on _lastSeen and _running.
//   3. Non-blocking goroutine to persist.
//
// Proto types used
// ────────────────
// Wire types (RegisterRequest, HeartbeatMessage, RegisterResponse) come from
// github.com/DyeAllPies/Helion-v2/proto (package proto, generated by protoc).
//
// Internal storage types (Node) come from
// github.com/DyeAllPies/Helion-v2/internal/proto/coordinatorpb (plain Go structs,
// not proto messages — serialised as JSON by BadgerJSONPersister).
//
// Key proto field notes:
//   HeartbeatMessage.Timestamp  — int64 Unix nanoseconds (not a proto Timestamp)
//   HeartbeatMessage            — has no Address field; address comes from Register
//   RegisterRequest.Certificate — DER bytes of node cert (populated in Phase 4)

package cluster

import (
	"context"
	"fmt"
	"log/slog"
	"sync"
	"sync/atomic"
	"time"

	cpb "github.com/DyeAllPies/Helion-v2/internal/proto/coordinatorpb"
	pb  "github.com/DyeAllPies/Helion-v2/proto"
)

// ── Persister ─────────────────────────────────────────────────────────────────

// Persister is the narrow storage interface used by the Registry.
// Tests inject NopPersister or MemPersister; production uses BadgerJSONPersister.
type Persister interface {
	SaveNode(ctx context.Context, n *cpb.Node) error
	LoadAllNodes(ctx context.Context) ([]*cpb.Node, error)
	AppendAudit(ctx context.Context, eventType, actor, target, detail string) error
}

// ── internal entry ────────────────────────────────────────────────────────────

// nodeEntry is the in-memory record for one registered node.
// Fields updated on every heartbeat are plain int32/int64 values accessed via
// the sync/atomic package — no mutex needed for those updates.
// address is stored as atomic.Value because Register() may update it
// concurrently with snapshot() calls from persist goroutines.
type nodeEntry struct {
	// Immutable after insertion into the map.
	nodeID       string
	registeredAt time.Time

	// address may be updated by Register() on node restart.
	// Stored as atomic.Value to avoid races with concurrent snapshot() calls.
	_address atomic.Value // holds string

	// Mutable; written atomically by HandleHeartbeat.
	_lastSeenNano int64 // Unix nanoseconds; 0 means "never seen"
	_runningJobs  int32
}

func (e *nodeEntry) storeAddress(addr string) {
	e._address.Store(addr)
}

func (e *nodeEntry) loadAddress() string {
	v := e._address.Load()
	if v == nil {
		return ""
	}
	return v.(string)
}

func (e *nodeEntry) storeLastSeen(t time.Time) {
	atomic.StoreInt64(&e._lastSeenNano, t.UnixNano())
}

func (e *nodeEntry) loadLastSeen() time.Time {
	ns := atomic.LoadInt64(&e._lastSeenNano)
	if ns == 0 {
		return time.Time{}
	}
	return time.Unix(0, ns)
}

func (e *nodeEntry) storeRunning(n int32) {
	atomic.StoreInt32(&e._runningJobs, n)
}

func (e *nodeEntry) loadRunning() int32 {
	return atomic.LoadInt32(&e._runningJobs)
}

func (e *nodeEntry) isHealthy(staleAfter time.Duration) bool {
	ls := e.loadLastSeen()
	return !ls.IsZero() && time.Since(ls) < staleAfter
}

func (e *nodeEntry) snapshot(staleAfter time.Duration) *cpb.Node {
	return &cpb.Node{
		NodeID:       e.nodeID,
		Address:      e.loadAddress(),
		Healthy:      e.isHealthy(staleAfter),
		LastSeen:     e.loadLastSeen(),
		RunningJobs:  e.loadRunning(),
		RegisteredAt: e.registeredAt,
	}
}

// ── Registry ──────────────────────────────────────────────────────────────────

// Registry maintains the authoritative in-memory map of worker nodes.
type Registry struct {
	mu    sync.RWMutex
	nodes map[string]*nodeEntry // keyed by nodeID

	persister         Persister
	heartbeatInterval time.Duration
	staleAfter        time.Duration // 2 × heartbeatInterval
	log               *slog.Logger
}

// NewRegistry creates a Registry.
func NewRegistry(p Persister, heartbeatInterval time.Duration, log *slog.Logger) *Registry {
	if log == nil {
		log = slog.Default()
	}
	return &Registry{
		nodes:             make(map[string]*nodeEntry),
		persister:         p,
		heartbeatInterval: heartbeatInterval,
		staleAfter:        2 * heartbeatInterval,
		log:               log,
	}
}

// ── Registration ──────────────────────────────────────────────────────────────

// Register handles the gRPC Register RPC.
// req is *proto.RegisterRequest from coordinator.pb.go:
//
//	NodeId      string
//	Address     string
//	Certificate []byte  (DER; used in Phase 4)
func (r *Registry) Register(ctx context.Context, req *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	now := time.Now()

	r.mu.Lock()
	entry, exists := r.nodes[req.NodeId]
	if !exists {
		entry = &nodeEntry{
			nodeID:       req.NodeId,
			registeredAt: now,
		}
		entry.storeAddress(req.Address)
		r.nodes[req.NodeId] = entry
	} else {
		// Node restarted — update address in case port changed.
		entry.storeAddress(req.Address)
	}
	entry.storeLastSeen(now)
	r.mu.Unlock()

	r.log.Info("node registered",
		slog.String("node_id", req.NodeId),
		slog.String("address", req.Address),
		slog.Bool("new", !exists),
	)

	// Persist and audit asynchronously — RPC response does not wait for disk.
	go func() {
		snap := entry.snapshot(r.staleAfter)
		if err := r.persister.SaveNode(context.Background(), snap); err != nil {
			r.log.Error("registry: persist on register",
				slog.String("node_id", req.NodeId), slog.Any("err", err))
		}
		_ = r.persister.AppendAudit(context.Background(),
			"node.registered", req.NodeId, req.NodeId,
			fmt.Sprintf("address=%s new=%v", req.Address, !exists))
	}()

	// SignedCertificate is populated by the auth layer (Phase 4).
	return &pb.RegisterResponse{NodeId: req.NodeId}, nil
}

// ── Heartbeat ─────────────────────────────────────────────────────────────────

// HandleHeartbeat processes one HeartbeatMessage from the gRPC bidi-stream.
// msg is *proto.HeartbeatMessage from coordinator.pb.go:
//
//	NodeId      string
//	Timestamp   int64   (Unix nanoseconds)
//	RunningJobs int32
//	CpuPercent  float64
//	MemPercent  float64
//
// Note: HeartbeatMessage has no Address field. The address is set at Register
// time and never changes unless the node re-registers.
//
// This method is lock-free for existing nodes.
func (r *Registry) HandleHeartbeat(ctx context.Context, msg *pb.HeartbeatMessage) error {
	// Use the node's reported timestamp; fall back to wall clock if zero.
	var seen time.Time
	if msg.Timestamp != 0 {
		seen = time.Unix(0, msg.Timestamp)
	} else {
		seen = time.Now()
	}

	// Fast path: existing node — look up under RLock, then release immediately.
	r.mu.RLock()
	entry := r.nodes[msg.NodeId]
	r.mu.RUnlock()

	// Slow path: heartbeat arrived before Register RPC (implicit registration).
	if entry == nil {
		r.mu.Lock()
		// Double-check after acquiring write lock.
		entry = r.nodes[msg.NodeId]
		if entry == nil {
			entry = &nodeEntry{
				nodeID:       msg.NodeId,
				registeredAt: seen,
			}
			entry.storeAddress("") // unknown until Register arrives
			r.nodes[msg.NodeId] = entry
			r.log.Info("registry: implicit registration via heartbeat",
				slog.String("node_id", msg.NodeId))
		}
		r.mu.Unlock()
	}

	// Atomic updates — no lock held from here.
	entry.storeLastSeen(seen)
	entry.storeRunning(msg.RunningJobs)

	// Persist asynchronously.
	go func() {
		snap := entry.snapshot(r.staleAfter)
		if err := r.persister.SaveNode(context.Background(), snap); err != nil {
			r.log.Error("registry: persist on heartbeat",
				slog.String("node_id", msg.NodeId), slog.Any("err", err))
		}
	}()

	return nil
}

// ── Prune ─────────────────────────────────────────────────────────────────────

// PruneStaleNodes marks nodes unhealthy if no heartbeat for >= staleAfter.
// No lock is held during any I/O or sleep — only a brief RLock to snapshot
// entry pointers. Returns the nodeIDs of stale nodes found.
func (r *Registry) PruneStaleNodes(ctx context.Context) []string {
	now := time.Now()

	// Snapshot entry pointers under RLock.
	r.mu.RLock()
	entries := make([]*nodeEntry, 0, len(r.nodes))
	for _, e := range r.nodes {
		entries = append(entries, e)
	}
	r.mu.RUnlock()

	var stale []string
	for _, e := range entries {
		ls := e.loadLastSeen()
		if ls.IsZero() || now.Sub(ls) >= r.staleAfter {
			stale = append(stale, e.nodeID)
			snap := e.snapshot(r.staleAfter) // Healthy=false because ls is old/zero

			r.log.Warn("registry: node stale",
				slog.String("node_id", e.nodeID),
				slog.String("address", e.loadAddress()),
				slog.Duration("since_last_heartbeat",
					now.Sub(ls).Round(time.Second)),
			)

			go func(n *cpb.Node) {
				if err := r.persister.SaveNode(ctx, n); err != nil {
					r.log.Error("registry: persist stale node",
						slog.String("node_id", n.NodeID), slog.Any("err", err))
				}
				_ = r.persister.AppendAudit(ctx,
					"node.stale", "coordinator", n.NodeID,
					fmt.Sprintf("no heartbeat for >%v", r.staleAfter))
			}(snap)
		}
	}
	return stale
}

// ── Reads ─────────────────────────────────────────────────────────────────────

// Snapshot returns a point-in-time copy of all nodes (healthy and unhealthy).
func (r *Registry) Snapshot() []*cpb.Node {
	r.mu.RLock()
	entries := make([]*nodeEntry, 0, len(r.nodes))
	for _, e := range r.nodes {
		entries = append(entries, e)
	}
	r.mu.RUnlock()

	nodes := make([]*cpb.Node, 0, len(entries))
	for _, e := range entries {
		nodes = append(nodes, e.snapshot(r.staleAfter))
	}
	return nodes
}

// HealthyNodes returns only healthy nodes, used by the Scheduler.
func (r *Registry) HealthyNodes() []*cpb.Node {
	r.mu.RLock()
	entries := make([]*nodeEntry, 0, len(r.nodes))
	for _, e := range r.nodes {
		entries = append(entries, e)
	}
	r.mu.RUnlock()

	var healthy []*cpb.Node
	for _, e := range entries {
		if e.isHealthy(r.staleAfter) {
			healthy = append(healthy, e.snapshot(r.staleAfter))
		}
	}
	return healthy
}

// Lookup returns the node with the given ID, or false if not found.
func (r *Registry) Lookup(nodeID string) (*cpb.Node, bool) {
	r.mu.RLock()
	e, ok := r.nodes[nodeID]
	r.mu.RUnlock()
	if !ok {
		return nil, false
	}
	return e.snapshot(r.staleAfter), true
}

// Len returns the total number of registered nodes.
func (r *Registry) Len() int {
	r.mu.RLock()
	n := len(r.nodes)
	r.mu.RUnlock()
	return n
}

// ── Restore ───────────────────────────────────────────────────────────────────

// Restore loads persisted nodes into memory on startup.
// Restored nodes start unhealthy — they must send a heartbeat to become healthy.
func (r *Registry) Restore(ctx context.Context) error {
	nodes, err := r.persister.LoadAllNodes(ctx)
	if err != nil {
		return fmt.Errorf("registry.Restore: %w", err)
	}

	r.mu.Lock()
	for _, n := range nodes {
		entry := &nodeEntry{
			nodeID:       n.NodeID,
			registeredAt: n.RegisteredAt,
		}
		entry.storeAddress(n.Address)
		// _lastSeenNano stays 0 → isHealthy() returns false until heartbeat arrives.
		r.nodes[n.NodeID] = entry
	}
	r.mu.Unlock()

	r.log.Info("registry: restored from persistence", slog.Int("count", len(nodes)))
	return nil
}
