// internal/cluster/registry.go
//
// Registry is the coordinator's authoritative view of all worker nodes.
//
// v1 bug fixes implemented here
// ──────────────────────────────
// CheckHealth() deadlock: eliminated by design. The coordinator never contacts
// nodes. Nodes push heartbeats in via the gRPC Heartbeat bidi-stream. Health
// is derived purely from the recency of the last heartbeat received.
//
// Concurrency model
// ─────────────────
// mu (RWMutex) protects the nodes map pointer:
//   - mu.Lock()  for: Register (new entry), Restore.
//   - mu.RLock() for: Snapshot, HealthyNodes, Lookup, Len.
//   - No lock for: updating _lastSeen / _running atomics on an existing
//     *nodeEntry — the pointer is stable once inserted; atomics self-synchronise.
//
// HandleHeartbeat is effectively lock-free for existing nodes:
//   1. RLock → look up pointer → RUnlock.
//   2. atomic.Store on _lastSeen and _running.
//   3. Non-blocking goroutine to persist.
//
// Proto types used
// ────────────────
// Wire types (RegisterRequest, HeartbeatMessage, RegisterResponse) come from
// github.com/DyeAllPies/Helion-v2/proto (package proto, generated by protoc).
//
// Internal storage types (Node) come from
// github.com/DyeAllPies/Helion-v2/internal/proto/coordinatorpb (plain Go structs,
// not proto messages — serialised as JSON by BadgerJSONPersister).
//
// Key proto field notes:
//   HeartbeatMessage.Timestamp  — int64 Unix nanoseconds (not a proto Timestamp)
//   HeartbeatMessage            — has no Address field; address comes from Register
//   RegisterRequest.Certificate — DER bytes of node cert (populated in Phase 4)
//
// File layout
// ───────────
//   registry.go           — Registry struct, NewRegistry, interfaces, setters
//   registry_node.go      — nodeEntry and node-ID validation
//   registry_register.go  — Register RPC handler
//   registry_heartbeat.go — HandleHeartbeat, PruneStaleNodes
//   registry_read.go      — Snapshot, HealthyNodes, Lookup, Len, Restore
//   registry_revoke.go    — RevokeNode, IsRevoked

package cluster

import (
	"context"
	"errors"
	"log/slog"
	"sync"
	"time"

	cpb "github.com/DyeAllPies/Helion-v2/internal/proto/coordinatorpb"
)

// ErrNodeNotRegistered is returned by HandleHeartbeat when the sender has not
// completed the Register RPC. The gRPC server maps this to codes.NotFound.
var ErrNodeNotRegistered = errors.New("registry: node not registered")

// StreamRevoker can forcibly close an active gRPC bidi-stream for a given node.
// Implemented by *grpcserver.Server; injected via Registry.SetStreamRevoker so
// the cluster package stays free of a grpcserver import.
type StreamRevoker interface {
	CancelStream(nodeID string)
}

// CertIssuer issues a coordinator-signed TLS certificate for a node.
// Implemented by *pqcrypto.CA; injected via Registry.SetCertIssuer so that
// Register can return a signed cert the node uses for its gRPC server.
type CertIssuer interface {
	IssueNodeCert(nodeID string) (certPEM, keyPEM []byte, err error)
}

// Persister is the narrow storage interface used by the Registry.
// Tests inject NopPersister or MemPersister; production uses BadgerJSONPersister.
type Persister interface {
	SaveNode(ctx context.Context, n *cpb.Node) error
	LoadAllNodes(ctx context.Context) ([]*cpb.Node, error)
	AppendAudit(ctx context.Context, eventType, actor, target, detail string) error
}

// ── Registry ──────────────────────────────────────────────────────────────────

// Registry maintains the authoritative in-memory map of worker nodes.
type Registry struct {
	mu    sync.RWMutex
	nodes map[string]*nodeEntry // keyed by nodeID

	revokedMu sync.RWMutex
	revoked   map[string]struct{} // nodeIDs that have been revoked

	streamRevokerMu sync.RWMutex
	streamRevoker   StreamRevoker // optional; closes active heartbeat streams on revocation

	certPinnerMu sync.RWMutex
	certPinner   CertPinner // optional; enforces cert fingerprint pinning at Register time

	certVerifierMu sync.RWMutex
	certVerifier   CertVerifier // optional; verifies ML-DSA out-of-band signature at Register time

	certIssuerMu sync.RWMutex
	certIssuer   CertIssuer // optional; issues coordinator-signed certs at Register time

	persister         Persister
	heartbeatInterval time.Duration
	staleAfter        time.Duration // 2 × heartbeatInterval
	log               *slog.Logger

	// auditWG tracks fire-and-forget background goroutines so Close can
	// wait for them during graceful shutdown. See AUDIT 2026-04-11-01/M1.
	auditWG sync.WaitGroup
}

// NewRegistry creates a Registry.
func NewRegistry(p Persister, heartbeatInterval time.Duration, log *slog.Logger) *Registry {
	if log == nil {
		log = slog.Default()
	}
	return &Registry{
		nodes:             make(map[string]*nodeEntry),
		revoked:           make(map[string]struct{}),
		persister:         p,
		heartbeatInterval: heartbeatInterval,
		staleAfter:        2 * heartbeatInterval,
		log:               log,
	}
}

// SetCertPinner injects a CertPinner so that Register enforces certificate
// fingerprint pinning: the first registration stores the pin, subsequent
// ones must present the same cert or be rejected.
func (r *Registry) SetCertPinner(cp CertPinner) {
	r.certPinnerMu.Lock()
	r.certPinner = cp
	r.certPinnerMu.Unlock()
}

// SetCertVerifier injects a CertVerifier so that Register validates the ML-DSA
// out-of-band signature on node certificates when ML-DSA is enabled on the CA.
func (r *Registry) SetCertVerifier(cv CertVerifier) {
	r.certVerifierMu.Lock()
	r.certVerifier = cv
	r.certVerifierMu.Unlock()
}

// SetCertIssuer injects a CertIssuer so that Register can return a
// coordinator-signed TLS certificate for the node's gRPC server.
func (r *Registry) SetCertIssuer(ci CertIssuer) {
	r.certIssuerMu.Lock()
	r.certIssuer = ci
	r.certIssuerMu.Unlock()
}

// SetStreamRevoker injects a StreamRevoker so that RevokeNode can immediately
// close the target node's active heartbeat stream.  Must be called before any
// RPCs arrive; safe to call concurrently but intended for startup wiring only.
func (r *Registry) SetStreamRevoker(sr StreamRevoker) {
	r.streamRevokerMu.Lock()
	r.streamRevoker = sr
	r.streamRevokerMu.Unlock()
}

// appendAuditAsync runs AppendAudit in a detached goroutine with a bounded
// timeout and logs at warn on failure. Tracked by auditWG so Close can join.
// See AUDIT 2026-04-11-01/M1.
func (r *Registry) appendAuditAsync(eventType, actor, target, detail string) {
	r.auditWG.Add(1)
	go func() {
		defer r.auditWG.Done()
		ctx, cancel := context.WithTimeout(context.Background(), auditWriteTimeout)
		defer cancel()
		if err := r.persister.AppendAudit(ctx, eventType, actor, target, detail); err != nil {
			r.log.Warn("audit write failed",
				slog.String("event", eventType),
				slog.String("target", target),
				slog.Any("err", err))
		}
	}()
}

// persistNodeAsync runs SaveNode in a detached goroutine with a bounded
// timeout and logs on failure. Tracked by auditWG so Close drains it.
func (r *Registry) persistNodeAsync(snap *cpb.Node) {
	r.auditWG.Add(1)
	go func() {
		defer r.auditWG.Done()
		ctx, cancel := context.WithTimeout(context.Background(), auditWriteTimeout)
		defer cancel()
		if err := r.persister.SaveNode(ctx, snap); err != nil {
			r.log.Error("registry: persist node async",
				slog.String("node_id", snap.NodeID), slog.Any("err", err))
		}
	}()
}

// Close waits for in-flight audit and persist goroutines to drain, bounded
// by timeout. Safe to call once during shutdown.
func (r *Registry) Close(timeout time.Duration) {
	done := make(chan struct{})
	go func() {
		r.auditWG.Wait()
		close(done)
	}()
	select {
	case <-done:
	case <-time.After(timeout):
		r.log.Warn("Registry.Close: background drain timed out", slog.Duration("timeout", timeout))
	}
}
