// internal/cluster/registry.go
//
// Registry is the coordinator's authoritative view of all worker nodes.
//
// v1 bug fixes implemented here
// ──────────────────────────────
// CheckHealth() deadlock: eliminated by design. The coordinator never contacts
// nodes. Nodes push heartbeats in via the gRPC Heartbeat bidi-stream. Health
// is derived purely from the recency of the last heartbeat received.
//
// Concurrency model
// ─────────────────
// mu (RWMutex) protects the nodes map pointer:
//   - mu.Lock()  for: Register (new entry), Restore.
//   - mu.RLock() for: Snapshot, HealthyNodes, Lookup, Len.
//   - No lock for: updating _lastSeen / _running atomics on an existing
//     *nodeEntry — the pointer is stable once inserted; atomics self-synchronise.
//
// HandleHeartbeat is effectively lock-free for existing nodes:
//   1. RLock → look up pointer → RUnlock.
//   2. atomic.Store on _lastSeen and _running.
//   3. Non-blocking goroutine to persist.
//
// Proto types used
// ────────────────
// Wire types (RegisterRequest, HeartbeatMessage, RegisterResponse) come from
// github.com/DyeAllPies/Helion-v2/proto (package proto, generated by protoc).
//
// Internal storage types (Node) come from
// github.com/DyeAllPies/Helion-v2/internal/proto/coordinatorpb (plain Go structs,
// not proto messages — serialised as JSON by BadgerJSONPersister).
//
// Key proto field notes:
//   HeartbeatMessage.Timestamp  — int64 Unix nanoseconds (not a proto Timestamp)
//   HeartbeatMessage            — has no Address field; address comes from Register
//   RegisterRequest.Certificate — DER bytes of node cert (populated in Phase 4)

package cluster

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"sync"
	"sync/atomic"
	"time"

	cpb "github.com/DyeAllPies/Helion-v2/internal/proto/coordinatorpb"
	pb  "github.com/DyeAllPies/Helion-v2/proto"
)

// ErrNodeNotRegistered is returned by HandleHeartbeat when the sender has not
// completed the Register RPC. The gRPC server maps this to codes.NotFound.
var ErrNodeNotRegistered = errors.New("registry: node not registered")

// StreamRevoker can forcibly close an active gRPC bidi-stream for a given node.
// Implemented by *grpcserver.Server; injected via Registry.SetStreamRevoker so
// the cluster package stays free of a grpcserver import.
type StreamRevoker interface {
	CancelStream(nodeID string)
}

// ── Persister ─────────────────────────────────────────────────────────────────

// Persister is the narrow storage interface used by the Registry.
// Tests inject NopPersister or MemPersister; production uses BadgerJSONPersister.
type Persister interface {
	SaveNode(ctx context.Context, n *cpb.Node) error
	LoadAllNodes(ctx context.Context) ([]*cpb.Node, error)
	AppendAudit(ctx context.Context, eventType, actor, target, detail string) error
}

// ── internal entry ────────────────────────────────────────────────────────────

// nodeEntry is the in-memory record for one registered node.
// Fields updated on every heartbeat are plain int32/int64 values accessed via
// the sync/atomic package — no mutex needed for those updates.
// address is stored as atomic.Value because Register() may update it
// concurrently with snapshot() calls from persist goroutines.
type nodeEntry struct {
	// Immutable after insertion into the map.
	nodeID       string
	registeredAt time.Time

	// address may be updated by Register() on node restart.
	// Stored as atomic.Value to avoid races with concurrent snapshot() calls.
	_address atomic.Value // holds string

	// Mutable; written atomically by HandleHeartbeat.
	_lastSeenNano int64 // Unix nanoseconds; 0 means "never seen"
	_runningJobs  int32
}

func (e *nodeEntry) storeAddress(addr string) {
	e._address.Store(addr)
}

func (e *nodeEntry) loadAddress() string {
	v := e._address.Load()
	if v == nil {
		return ""
	}
	return v.(string)
}

func (e *nodeEntry) storeLastSeen(t time.Time) {
	atomic.StoreInt64(&e._lastSeenNano, t.UnixNano())
}

func (e *nodeEntry) loadLastSeen() time.Time {
	ns := atomic.LoadInt64(&e._lastSeenNano)
	if ns == 0 {
		return time.Time{}
	}
	return time.Unix(0, ns)
}

func (e *nodeEntry) storeRunning(n int32) {
	atomic.StoreInt32(&e._runningJobs, n)
}

func (e *nodeEntry) loadRunning() int32 {
	return atomic.LoadInt32(&e._runningJobs)
}

func (e *nodeEntry) isHealthy(staleAfter time.Duration) bool {
	ls := e.loadLastSeen()
	return !ls.IsZero() && time.Since(ls) < staleAfter
}

func (e *nodeEntry) snapshot(staleAfter time.Duration) *cpb.Node {
	return &cpb.Node{
		NodeID:       e.nodeID,
		Address:      e.loadAddress(),
		Healthy:      e.isHealthy(staleAfter),
		LastSeen:     e.loadLastSeen(),
		RunningJobs:  e.loadRunning(),
		RegisteredAt: e.registeredAt,
	}
}

// ── Registry ──────────────────────────────────────────────────────────────────

// Registry maintains the authoritative in-memory map of worker nodes.
type Registry struct {
	mu    sync.RWMutex
	nodes map[string]*nodeEntry // keyed by nodeID

	revokedMu sync.RWMutex
	revoked   map[string]struct{} // nodeIDs that have been revoked

	streamRevokerMu sync.RWMutex
	streamRevoker   StreamRevoker // optional; closes active heartbeat streams on revocation

	certPinnerMu sync.RWMutex
	certPinner   CertPinner // optional; enforces cert fingerprint pinning at Register time

	certVerifierMu sync.RWMutex
	certVerifier   CertVerifier // optional; verifies ML-DSA out-of-band signature at Register time

	persister         Persister
	heartbeatInterval time.Duration
	staleAfter        time.Duration // 2 × heartbeatInterval
	log               *slog.Logger
}

// NewRegistry creates a Registry.
func NewRegistry(p Persister, heartbeatInterval time.Duration, log *slog.Logger) *Registry {
	if log == nil {
		log = slog.Default()
	}
	return &Registry{
		nodes:             make(map[string]*nodeEntry),
		revoked:           make(map[string]struct{}),
		persister:         p,
		heartbeatInterval: heartbeatInterval,
		staleAfter:        2 * heartbeatInterval,
		log:               log,
	}
}

// SetCertPinner injects a CertPinner so that Register enforces certificate
// fingerprint pinning: the first registration stores the pin, subsequent
// ones must present the same cert or be rejected.
func (r *Registry) SetCertPinner(cp CertPinner) {
	r.certPinnerMu.Lock()
	r.certPinner = cp
	r.certPinnerMu.Unlock()
}

// SetCertVerifier injects a CertVerifier so that Register validates the ML-DSA
// out-of-band signature on node certificates when ML-DSA is enabled on the CA.
func (r *Registry) SetCertVerifier(cv CertVerifier) {
	r.certVerifierMu.Lock()
	r.certVerifier = cv
	r.certVerifierMu.Unlock()
}

// SetStreamRevoker injects a StreamRevoker so that RevokeNode can immediately
// close the target node's active heartbeat stream.  Must be called before any
// RPCs arrive; safe to call concurrently but intended for startup wiring only.
func (r *Registry) SetStreamRevoker(sr StreamRevoker) {
	r.streamRevokerMu.Lock()
	r.streamRevoker = sr
	r.streamRevokerMu.Unlock()
}

// ── Registration ──────────────────────────────────────────────────────────────

// Register handles the gRPC Register RPC.
// req is *proto.RegisterRequest from coordinator.pb.go:
//
//	NodeId      string
//	Address     string
//	Certificate []byte  (DER; used in Phase 4)
func (r *Registry) Register(ctx context.Context, req *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	// Phase 4: reject registration from a revoked node.
	if r.IsRevoked(req.NodeId) {
		r.log.Warn("registry: revoked node attempted re-registration",
			slog.String("node_id", req.NodeId))
		return nil, fmt.Errorf("node %s is revoked: re-register with a new certificate", req.NodeId)
	}

	// Phase 4: certificate checks (pinning + ML-DSA) when the request carries
	// DER cert bytes.
	if len(req.Certificate) > 0 {
		// ML-DSA out-of-band signature verification: ensures the cert was
		// issued by this coordinator's CA (not a rogue CA with a stolen ECDSA key).
		r.certVerifierMu.RLock()
		cv := r.certVerifier
		r.certVerifierMu.RUnlock()

		if cv != nil {
			if err := cv.VerifyNodeCertMLDSA(req.Certificate); err != nil {
				r.log.Warn("registry: ML-DSA verification failed — rejecting registration",
					slog.String("node_id", req.NodeId), slog.Any("err", err))
				return nil, fmt.Errorf("node %s: ML-DSA signature verification failed", req.NodeId)
			}
		}

		// Certificate pinning: enforce fingerprint consistency across
		// re-registrations so a newly-issued cert can't silently replace the old one.
		r.certPinnerMu.RLock()
		cp := r.certPinner
		r.certPinnerMu.RUnlock()

		if cp != nil {
			fp := CertFingerprint(req.Certificate)
			stored, err := cp.GetPin(ctx, req.NodeId)
			if err != nil {
				// No pin stored yet — record it for future registrations.
				if perr := cp.SetPin(ctx, req.NodeId, fp); perr != nil {
					r.log.Error("registry: store cert pin failed",
						slog.String("node_id", req.NodeId), slog.Any("err", perr))
				} else {
					r.log.Info("registry: cert pin stored",
						slog.String("node_id", req.NodeId))
				}
			} else if stored != fp {
				r.log.Warn("registry: cert fingerprint mismatch — rejecting registration",
					slog.String("node_id", req.NodeId))
				return nil, ErrCertFingerprintMismatch
			}
		}
	}

	now := time.Now()

	r.mu.Lock()
	entry, exists := r.nodes[req.NodeId]
	if !exists {
		entry = &nodeEntry{
			nodeID:       req.NodeId,
			registeredAt: now,
		}
		entry.storeAddress(req.Address)
		r.nodes[req.NodeId] = entry
	} else {
		// Node restarted — update address in case port changed.
		entry.storeAddress(req.Address)
	}
	entry.storeLastSeen(now)
	r.mu.Unlock()

	r.log.Info("node registered",
		slog.String("node_id", req.NodeId),
		slog.String("address", req.Address),
		slog.Bool("new", !exists),
	)

	// Persist and audit asynchronously — RPC response does not wait for disk.
	go func() {
		snap := entry.snapshot(r.staleAfter)
		if err := r.persister.SaveNode(context.Background(), snap); err != nil {
			r.log.Error("registry: persist on register",
				slog.String("node_id", req.NodeId), slog.Any("err", err))
		}
		_ = r.persister.AppendAudit(context.Background(),
			"node.registered", req.NodeId, req.NodeId,
			fmt.Sprintf("address=%s new=%v", req.Address, !exists))
	}()

	// SignedCertificate is populated by the auth layer (Phase 4).
	return &pb.RegisterResponse{NodeId: req.NodeId}, nil
}

// ── Heartbeat ─────────────────────────────────────────────────────────────────

// HandleHeartbeat processes one HeartbeatMessage from the gRPC bidi-stream.
// msg is *proto.HeartbeatMessage from coordinator.pb.go:
//
//	NodeId      string
//	Timestamp   int64   (Unix nanoseconds)
//	RunningJobs int32
//	CpuPercent  float64
//	MemPercent  float64
//
// Note: HeartbeatMessage has no Address field. The address is set at Register
// time and never changes unless the node re-registers.
//
// This method is lock-free for existing nodes.
func (r *Registry) HandleHeartbeat(ctx context.Context, msg *pb.HeartbeatMessage) error {
	// Always use the coordinator's wall clock for last-seen. Trusting the
	// node-reported Timestamp allows a node to spoof its health status.
	seen := time.Now()

	// Fast path: existing node — look up under RLock, then release immediately.
	r.mu.RLock()
	entry := r.nodes[msg.NodeId]
	r.mu.RUnlock()

	// Reject heartbeats from nodes that have not completed Register. Implicit
	// registration would let a node bypass the credential exchange in Register().
	if entry == nil {
		r.log.Warn("registry: heartbeat from unregistered node, rejecting",
			slog.String("node_id", msg.NodeId))
		return ErrNodeNotRegistered
	}

	// Atomic updates — no lock held from here.
	entry.storeLastSeen(seen)
	entry.storeRunning(msg.RunningJobs)

	// Persist asynchronously.
	go func() {
		snap := entry.snapshot(r.staleAfter)
		if err := r.persister.SaveNode(context.Background(), snap); err != nil {
			r.log.Error("registry: persist on heartbeat",
				slog.String("node_id", msg.NodeId), slog.Any("err", err))
		}
	}()

	return nil
}

// ── Prune ─────────────────────────────────────────────────────────────────────

// PruneStaleNodes marks nodes unhealthy if no heartbeat for >= staleAfter.
// No lock is held during any I/O or sleep — only a brief RLock to snapshot
// entry pointers. Returns the nodeIDs of stale nodes found.
func (r *Registry) PruneStaleNodes(ctx context.Context) []string {
	now := time.Now()

	// Snapshot entry pointers under RLock.
	r.mu.RLock()
	entries := make([]*nodeEntry, 0, len(r.nodes))
	for _, e := range r.nodes {
		entries = append(entries, e)
	}
	r.mu.RUnlock()

	var stale []string
	for _, e := range entries {
		ls := e.loadLastSeen()
		if ls.IsZero() || now.Sub(ls) >= r.staleAfter {
			stale = append(stale, e.nodeID)
			snap := e.snapshot(r.staleAfter) // Healthy=false because ls is old/zero

			r.log.Warn("registry: node stale",
				slog.String("node_id", e.nodeID),
				slog.String("address", e.loadAddress()),
				slog.Duration("since_last_heartbeat",
					now.Sub(ls).Round(time.Second)),
			)

			go func(n *cpb.Node) {
				if err := r.persister.SaveNode(ctx, n); err != nil {
					r.log.Error("registry: persist stale node",
						slog.String("node_id", n.NodeID), slog.Any("err", err))
				}
				_ = r.persister.AppendAudit(ctx,
					"node.stale", "coordinator", n.NodeID,
					fmt.Sprintf("no heartbeat for >%v", r.staleAfter))
			}(snap)
		}
	}
	return stale
}

// ── Reads ─────────────────────────────────────────────────────────────────────

// Snapshot returns a point-in-time copy of all nodes (healthy and unhealthy).
func (r *Registry) Snapshot() []*cpb.Node {
	r.mu.RLock()
	entries := make([]*nodeEntry, 0, len(r.nodes))
	for _, e := range r.nodes {
		entries = append(entries, e)
	}
	r.mu.RUnlock()

	nodes := make([]*cpb.Node, 0, len(entries))
	for _, e := range entries {
		nodes = append(nodes, e.snapshot(r.staleAfter))
	}
	return nodes
}

// HealthyNodes returns only healthy nodes, used by the Scheduler.
func (r *Registry) HealthyNodes() []*cpb.Node {
	r.mu.RLock()
	entries := make([]*nodeEntry, 0, len(r.nodes))
	for _, e := range r.nodes {
		entries = append(entries, e)
	}
	r.mu.RUnlock()

	var healthy []*cpb.Node
	for _, e := range entries {
		if e.isHealthy(r.staleAfter) {
			healthy = append(healthy, e.snapshot(r.staleAfter))
		}
	}
	return healthy
}

// Lookup returns the node with the given ID, or false if not found.
func (r *Registry) Lookup(nodeID string) (*cpb.Node, bool) {
	r.mu.RLock()
	e, ok := r.nodes[nodeID]
	r.mu.RUnlock()
	if !ok {
		return nil, false
	}
	return e.snapshot(r.staleAfter), true
}

// Len returns the total number of registered nodes.
func (r *Registry) Len() int {
	r.mu.RLock()
	n := len(r.nodes)
	r.mu.RUnlock()
	return n
}

// CountTotal implements metrics.NodeCounter.
func (r *Registry) CountTotal(_ context.Context) (int, error) {
	return r.Len(), nil
}

// CountHealthy implements metrics.NodeCounter.
func (r *Registry) CountHealthy(_ context.Context) (int, error) {
	return len(r.HealthyNodes()), nil
}

// ── Revocation ────────────────────────────────────────────────────────────────

// RevokeNode marks a node as revoked and forcibly closes its active heartbeat
// stream (if a StreamRevoker is wired in).  The node must re-register with a
// new node ID to reconnect.
func (r *Registry) RevokeNode(ctx context.Context, nodeID, reason string) error {
	r.revokedMu.Lock()
	r.revoked[nodeID] = struct{}{}
	r.revokedMu.Unlock()

	// Remove from active nodes map so it won't be scheduled.
	r.mu.Lock()
	delete(r.nodes, nodeID)
	r.mu.Unlock()

	// Forcibly close the node's active heartbeat stream so it receives
	// codes.Unauthenticated without waiting for the next heartbeat interval.
	r.streamRevokerMu.RLock()
	sr := r.streamRevoker
	r.streamRevokerMu.RUnlock()
	if sr != nil {
		sr.CancelStream(nodeID)
	}

	// Clear the cert pin so a new cert can be pinned on fresh registration.
	r.certPinnerMu.RLock()
	cp := r.certPinner
	r.certPinnerMu.RUnlock()
	if cp != nil {
		if err := cp.DeletePin(ctx, nodeID); err != nil {
			r.log.Warn("registry: delete cert pin failed",
				slog.String("node_id", nodeID), slog.Any("err", err))
		}
	}

	r.log.Warn("registry: node revoked",
		slog.String("node_id", nodeID),
		slog.String("reason", reason))

	go func() {
		_ = r.persister.AppendAudit(context.Background(),
			"node.revoked", "coordinator", nodeID,
			fmt.Sprintf("reason=%s", reason))
	}()
	return nil
}

// IsRevoked reports whether nodeID has been revoked.
// Safe for concurrent use; called on every incoming gRPC RPC.
func (r *Registry) IsRevoked(nodeID string) bool {
	r.revokedMu.RLock()
	_, ok := r.revoked[nodeID]
	r.revokedMu.RUnlock()
	return ok
}

// ── Restore ───────────────────────────────────────────────────────────────────

// Restore loads persisted nodes into memory on startup.
// Restored nodes start unhealthy — they must send a heartbeat to become healthy.
func (r *Registry) Restore(ctx context.Context) error {
	nodes, err := r.persister.LoadAllNodes(ctx)
	if err != nil {
		return fmt.Errorf("registry.Restore: %w", err)
	}

	r.mu.Lock()
	for _, n := range nodes {
		entry := &nodeEntry{
			nodeID:       n.NodeID,
			registeredAt: n.RegisteredAt,
		}
		entry.storeAddress(n.Address)
		// _lastSeenNano stays 0 → isHealthy() returns false until heartbeat arrives.
		r.nodes[n.NodeID] = entry
	}
	r.mu.Unlock()

	r.log.Info("registry: restored from persistence", slog.Int("count", len(nodes)))
	return nil
}
