version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  govet:
    enable-all: true

issues:
  exclude-rules:
    - path: "proto/"
      linters:
        - all