linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck

issues:
  exclude-rules:
    - path: "proto/"
      linters:
        - errcheck
        - staticcheck
        - typecheck