// proto/coordinator.proto
//
// Services and messages exposed by the Helion coordinator.
//
// IMPORTANT: The generated .pb.go files in this directory were hand-edited
// in early phases to add fields (e.g. JobResult.Success, ExitCode) that
// were not in the .proto. These fields have since been added to the .proto
// to bring it back in sync. Always regenerate after editing .proto files
// and verify the build compiles cleanly.
//
// Regenerate with (from repo root):
//   protoc --go_out=proto --go_opt=paths=source_relative \
//          --go-grpc_out=proto --go-grpc_opt=paths=source_relative \
//          --proto_path=proto coordinator.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: coordinator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeCommand is an instruction the coordinator can piggyback on a HeartbeatAck.
type NodeCommand int32

const (
	NodeCommand_NODE_COMMAND_NONE     NodeCommand = 0
	NodeCommand_NODE_COMMAND_SHUTDOWN NodeCommand = 1 // coordinator requests graceful node shutdown
	NodeCommand_NODE_COMMAND_REJOIN   NodeCommand = 2 // coordinator requests re-registration
)

// Enum value maps for NodeCommand.
var (
	NodeCommand_name = map[int32]string{
		0: "NODE_COMMAND_NONE",
		1: "NODE_COMMAND_SHUTDOWN",
		2: "NODE_COMMAND_REJOIN",
	}
	NodeCommand_value = map[string]int32{
		"NODE_COMMAND_NONE":     0,
		"NODE_COMMAND_SHUTDOWN": 1,
		"NODE_COMMAND_REJOIN":   2,
	}
)

func (x NodeCommand) Enum() *NodeCommand {
	p := new(NodeCommand)
	*p = x
	return p
}

func (x NodeCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_coordinator_proto_enumTypes[0].Descriptor()
}

func (NodeCommand) Type() protoreflect.EnumType {
	return &file_coordinator_proto_enumTypes[0]
}

func (x NodeCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeCommand.Descriptor instead.
func (NodeCommand) EnumDescriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNKNOWN     JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1
	JobStatus_JOB_STATUS_DISPATCHING JobStatus = 2
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 3
	JobStatus_JOB_STATUS_COMPLETED   JobStatus = 4
	JobStatus_JOB_STATUS_FAILED      JobStatus = 5
	JobStatus_JOB_STATUS_TIMEOUT     JobStatus = 6
	JobStatus_JOB_STATUS_LOST        JobStatus = 7
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNKNOWN",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_DISPATCHING",
		3: "JOB_STATUS_RUNNING",
		4: "JOB_STATUS_COMPLETED",
		5: "JOB_STATUS_FAILED",
		6: "JOB_STATUS_TIMEOUT",
		7: "JOB_STATUS_LOST",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNKNOWN":     0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_DISPATCHING": 2,
		"JOB_STATUS_RUNNING":     3,
		"JOB_STATUS_COMPLETED":   4,
		"JOB_STATUS_FAILED":      5,
		"JOB_STATUS_TIMEOUT":     6,
		"JOB_STATUS_LOST":        7,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_coordinator_proto_enumTypes[1].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_coordinator_proto_enumTypes[1]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{1}
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier chosen by the node (e.g. hostname + port).
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Network address the coordinator should use to dispatch jobs.
	// Format: "host:port".
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// DER-encoded X.509 certificate presented by the node for cert pinning and
	// ML-DSA out-of-band signature verification.
	// Empty on first registration if the node has no existing certificate.
	Certificate []byte `protobuf:"bytes,3,opt,name=certificate,proto3" json:"certificate,omitempty"`
	// Free-form labels the scheduler uses for node_selector matching.
	// Sources on the node side: HELION_LABEL_* env vars (operator set)
	// plus best-effort auto-detection (gpu=<model> from nvidia-smi,
	// os=linux|darwin|windows, arch=amd64|arm64). Persisted on the
	// coordinator's Node record; never mutated after registration.
	Labels        map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DER-encoded signed X.509 certificate for this node.
	CertDer []byte `protobuf:"bytes,1,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`
	// DER-encoded coordinator CA certificate so the node can verify future RPCs.
	CaCertDer []byte `protobuf:"bytes,2,opt,name=ca_cert_der,json=caCertDer,proto3" json:"ca_cert_der,omitempty"`
	// Heartbeat interval the node should use.  The coordinator sets this
	// cluster-wide; nodes must not use a self-chosen interval.
	HeartbeatIntervalSeconds int64 `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	// Echoed node ID (used by tests and simple clients).
	NodeId string `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// PEM-encoded signed certificate + private key for the node's gRPC server.
	// Issued by the coordinator's CA so dispatchers can verify node identity.
	SignedCertificate []byte `protobuf:"bytes,5,opt,name=signed_certificate,json=signedCertificate,proto3" json:"signed_certificate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *RegisterResponse) GetCaCertDer() []byte {
	if x != nil {
		return x.CaCertDer
	}
	return nil
}

func (x *RegisterResponse) GetHeartbeatIntervalSeconds() int64 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetSignedCertificate() []byte {
	if x != nil {
		return x.SignedCertificate
	}
	return nil
}

type HeartbeatMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	NodeId  string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// Current number of jobs actively running on this node.
	RunningJobs int32 `protobuf:"varint,3,opt,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	// Monotonically increasing sequence number.  The coordinator can detect
	// dropped messages by checking for gaps.
	Seq    uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	SentAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Node capacity — reported on every heartbeat so the coordinator can
	// make resource-aware scheduling decisions.
	CpuMillicores    uint32 `protobuf:"varint,6,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`            // total CPU capacity (e.g., 4000 = 4 cores)
	TotalMemoryBytes uint64 `protobuf:"varint,7,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"` // total memory in bytes
	MaxSlots         uint32 `protobuf:"varint,8,opt,name=max_slots,json=maxSlots,proto3" json:"max_slots,omitempty"`                           // max concurrent job slots
	// Whole-GPU count — no MIG slicing, no fractional sharing. Zero on
	// CPU-only nodes; the scheduler uses this as a bin-packing
	// dimension alongside CPU/memory/slots. Per-device attributes
	// (memory, model) are carried via node labels, not here.
	TotalGpus     uint32 `protobuf:"varint,9,opt,name=total_gpus,json=totalGpus,proto3" json:"total_gpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatMessage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HeartbeatMessage) GetRunningJobs() int32 {
	if x != nil {
		return x.RunningJobs
	}
	return 0
}

func (x *HeartbeatMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *HeartbeatMessage) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *HeartbeatMessage) GetCpuMillicores() uint32 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *HeartbeatMessage) GetTotalMemoryBytes() uint64 {
	if x != nil {
		return x.TotalMemoryBytes
	}
	return 0
}

func (x *HeartbeatMessage) GetMaxSlots() uint32 {
	if x != nil {
		return x.MaxSlots
	}
	return 0
}

func (x *HeartbeatMessage) GetTotalGpus() uint32 {
	if x != nil {
		return x.TotalGpus
	}
	return 0
}

type HeartbeatAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // echoes the HeartbeatMessage.seq being acknowledged
	// Optional command for the node.  Empty means "nothing to do".
	Command       NodeCommand `protobuf:"varint,2,opt,name=command,proto3,enum=helion.NodeCommand" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatAck) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *HeartbeatAck) GetCommand() NodeCommand {
	if x != nil {
		return x.Command
	}
	return NodeCommand_NODE_COMMAND_NONE
}

type JobResult struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	JobId      string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	NodeId     string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success    bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"` // true if exit code 0
	ExitCode   int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error      string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                           // populated when success == false
	StartedAt  int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // Unix nanoseconds
	FinishedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	// runtime identifies the backend that executed the job ("go" or "rust").
	Runtime string `protobuf:"bytes,8,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Step 2 — resolved artifact outputs from the node's stager. Populated
	// only on successful runs (the stager skips uploads otherwise), one
	// entry per binding declared on the original Job.Outputs.
	Outputs       []*ArtifactOutput `protobuf:"bytes,9,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JobResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JobResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *JobResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobResult) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *JobResult) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *JobResult) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *JobResult) GetOutputs() []*ArtifactOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// ArtifactOutput is a resolved reference to an artifact uploaded by the
// node agent after a job exits zero. Name matches the binding declared
// at submit time; URI is what the artifact store assigned.
type ArtifactOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	LocalPath     string                 `protobuf:"bytes,5,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"` // original working-directory-relative path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactOutput) Reset() {
	*x = ArtifactOutput{}
	mi := &file_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactOutput) ProtoMessage() {}

func (x *ArtifactOutput) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactOutput.ProtoReflect.Descriptor instead.
func (*ArtifactOutput) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *ArtifactOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactOutput) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ArtifactOutput) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ArtifactOutput) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ArtifactOutput) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // raw stdout/stderr bytes
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`  // chunk sequence number for ordering on reassembly
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *LogChunk) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LogChunk) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LogChunk) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

// Ack is a minimal acknowledgement for one-way RPCs.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Node is the persisted record for a registered worker node.
// Stored under nodes/{address} in BadgerDB.
type Node struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	NodeId  string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Healthy bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// last_seen is the wall-clock time of the most recent heartbeat received.
	// The coordinator derives health from this: healthy iff
	// now - last_seen < 2 × heartbeat_interval.
	LastSeen *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// running_jobs is the node's self-reported count from the last heartbeat.
	RunningJobs  int32                  `protobuf:"varint,5,opt,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	RegisteredAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	// Labels reported at registration time; used by the scheduler's
	// node_selector filter. Frozen after Register — re-registering with
	// a different label set requires a fresh certificate.
	Labels        map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *Node) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Node) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Node) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *Node) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Node) GetRunningJobs() int32 {
	if x != nil {
		return x.RunningJobs
	}
	return 0
}

func (x *Node) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *Node) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Job is the persisted record for a scheduled job.
// Stored under jobs/{id} in BadgerDB.
type Job struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId       string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // address of the node this was dispatched to
	Command      string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Args         []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Status       JobStatus              `protobuf:"varint,5,opt,name=status,proto3,enum=helion.JobStatus" json:"status,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DispatchedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=dispatched_at,json=dispatchedAt,proto3" json:"dispatched_at,omitempty"`
	FinishedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Error        string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"` // populated for FAILED / TIMEOUT / LOST
	// env holds arbitrary key-value pairs forwarded to the job process.
	Env map[string]string `protobuf:"bytes,10,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// timeout_seconds caps how long a job may run. 0 means no limit.
	TimeoutSeconds int64 `protobuf:"varint,11,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// runtime records which runtime backend executed the job ("go" or "rust").
	// Set at dispatch time based on the target node's configured runtime.
	Runtime       string `protobuf:"bytes,12,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Job) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Job) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNKNOWN
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetDispatchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DispatchedAt
	}
	return nil
}

func (x *Job) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Job) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Job) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Job) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Job) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

// AuditEvent is written to audit/{timestamp}-{id} on every security-relevant
// or job-lifecycle event.  Append-only; never mutated after write.
type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // e.g. "node.registered", "job.dispatched"
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`                          // node_id or "coordinator"
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`                        // job_id or node_id being acted on
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`                        // human-readable summary
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *AuditEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AuditEvent) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditEvent) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AuditEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AuditEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_coordinator_proto protoreflect.FileDescriptor

const file_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x11coordinator.proto\x12\x06helion\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x01\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12 \n" +
	"\vcertificate\x18\x03 \x01(\fR\vcertificate\x12;\n" +
	"\x06labels\x18\x04 \x03(\v2#.helion.RegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x01\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bcert_der\x18\x01 \x01(\fR\acertDer\x12\x1e\n" +
	"\vca_cert_der\x18\x02 \x01(\fR\tcaCertDer\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\x03R\x18heartbeatIntervalSeconds\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12-\n" +
	"\x12signed_certificate\x18\x05 \x01(\fR\x11signedCertificate\"\xc0\x02\n" +
	"\x10HeartbeatMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12!\n" +
	"\frunning_jobs\x18\x03 \x01(\x05R\vrunningJobs\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x123\n" +
	"\asent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12%\n" +
	"\x0ecpu_millicores\x18\x06 \x01(\rR\rcpuMillicores\x12,\n" +
	"\x12total_memory_bytes\x18\a \x01(\x04R\x10totalMemoryBytes\x12\x1b\n" +
	"\tmax_slots\x18\b \x01(\rR\bmaxSlots\x12\x1d\n" +
	"\n" +
	"total_gpus\x18\t \x01(\rR\ttotalGpus\"O\n" +
	"\fHeartbeatAck\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12-\n" +
	"\acommand\x18\x02 \x01(\x0e2\x13.helion.NodeCommandR\acommand\"\xb0\x02\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x18\n" +
	"\aruntime\x18\b \x01(\tR\aruntime\x120\n" +
	"\aoutputs\x18\t \x03(\v2\x16.helion.ArtifactOutputR\aoutputs\"\x81\x01\n" +
	"\x0eArtifactOutput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"local_path\x18\x05 \x01(\tR\tlocalPath\"\x95\x01\n" +
	"\bLogChunk\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x123\n" +
	"\asent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xdd\x02\n" +
	"\x04Node\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12!\n" +
	"\frunning_jobs\x18\x05 \x01(\x05R\vrunningJobs\x12?\n" +
	"\rregistered_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x120\n" +
	"\x06labels\x18\a \x03(\v2\x18.helion.Node.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12)\n" +
	"\x06status\x18\x05 \x01(\x0e2\x11.helion.JobStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12?\n" +
	"\rdispatched_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fdispatchedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12&\n" +
	"\x03env\x18\n" +
	" \x03(\v2\x14.helion.Job.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\v \x01(\x03R\x0etimeoutSeconds\x12\x18\n" +
	"\aruntime\x18\f \x01(\tR\aruntime\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x01\n" +
	"\n" +
	"AuditEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt*X\n" +
	"\vNodeCommand\x12\x15\n" +
	"\x11NODE_COMMAND_NONE\x10\x00\x12\x19\n" +
	"\x15NODE_COMMAND_SHUTDOWN\x10\x01\x12\x17\n" +
	"\x13NODE_COMMAND_REJOIN\x10\x02*\xcd\x01\n" +
	"\tJobStatus\x12\x16\n" +
	"\x12JOB_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16JOB_STATUS_DISPATCHING\x10\x02\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x03\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x04\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x05\x12\x16\n" +
	"\x12JOB_STATUS_TIMEOUT\x10\x06\x12\x13\n" +
	"\x0fJOB_STATUS_LOST\x10\a2\xf3\x01\n" +
	"\x12CoordinatorService\x12=\n" +
	"\bRegister\x12\x17.helion.RegisterRequest\x1a\x18.helion.RegisterResponse\x12?\n" +
	"\tHeartbeat\x12\x18.helion.HeartbeatMessage\x1a\x14.helion.HeartbeatAck(\x010\x01\x12.\n" +
	"\fReportResult\x12\x11.helion.JobResult\x1a\v.helion.Ack\x12-\n" +
	"\n" +
	"StreamLogs\x12\x10.helion.LogChunk\x1a\v.helion.Ack(\x01B'Z%github.com/DyeAllPies/Helion-v2/protob\x06proto3"

var (
	file_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_proto_rawDescData []byte
)

func file_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)))
	})
	return file_coordinator_proto_rawDescData
}

var file_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_coordinator_proto_goTypes = []any{
	(NodeCommand)(0),              // 0: helion.NodeCommand
	(JobStatus)(0),                // 1: helion.JobStatus
	(*RegisterRequest)(nil),       // 2: helion.RegisterRequest
	(*RegisterResponse)(nil),      // 3: helion.RegisterResponse
	(*HeartbeatMessage)(nil),      // 4: helion.HeartbeatMessage
	(*HeartbeatAck)(nil),          // 5: helion.HeartbeatAck
	(*JobResult)(nil),             // 6: helion.JobResult
	(*ArtifactOutput)(nil),        // 7: helion.ArtifactOutput
	(*LogChunk)(nil),              // 8: helion.LogChunk
	(*Ack)(nil),                   // 9: helion.Ack
	(*Node)(nil),                  // 10: helion.Node
	(*Job)(nil),                   // 11: helion.Job
	(*AuditEvent)(nil),            // 12: helion.AuditEvent
	nil,                           // 13: helion.RegisterRequest.LabelsEntry
	nil,                           // 14: helion.Node.LabelsEntry
	nil,                           // 15: helion.Job.EnvEntry
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_coordinator_proto_depIdxs = []int32{
	13, // 0: helion.RegisterRequest.labels:type_name -> helion.RegisterRequest.LabelsEntry
	16, // 1: helion.HeartbeatMessage.sent_at:type_name -> google.protobuf.Timestamp
	0,  // 2: helion.HeartbeatAck.command:type_name -> helion.NodeCommand
	16, // 3: helion.JobResult.finished_at:type_name -> google.protobuf.Timestamp
	7,  // 4: helion.JobResult.outputs:type_name -> helion.ArtifactOutput
	16, // 5: helion.LogChunk.sent_at:type_name -> google.protobuf.Timestamp
	16, // 6: helion.Node.last_seen:type_name -> google.protobuf.Timestamp
	16, // 7: helion.Node.registered_at:type_name -> google.protobuf.Timestamp
	14, // 8: helion.Node.labels:type_name -> helion.Node.LabelsEntry
	1,  // 9: helion.Job.status:type_name -> helion.JobStatus
	16, // 10: helion.Job.created_at:type_name -> google.protobuf.Timestamp
	16, // 11: helion.Job.dispatched_at:type_name -> google.protobuf.Timestamp
	16, // 12: helion.Job.finished_at:type_name -> google.protobuf.Timestamp
	15, // 13: helion.Job.env:type_name -> helion.Job.EnvEntry
	16, // 14: helion.AuditEvent.occurred_at:type_name -> google.protobuf.Timestamp
	2,  // 15: helion.CoordinatorService.Register:input_type -> helion.RegisterRequest
	4,  // 16: helion.CoordinatorService.Heartbeat:input_type -> helion.HeartbeatMessage
	6,  // 17: helion.CoordinatorService.ReportResult:input_type -> helion.JobResult
	8,  // 18: helion.CoordinatorService.StreamLogs:input_type -> helion.LogChunk
	3,  // 19: helion.CoordinatorService.Register:output_type -> helion.RegisterResponse
	5,  // 20: helion.CoordinatorService.Heartbeat:output_type -> helion.HeartbeatAck
	9,  // 21: helion.CoordinatorService.ReportResult:output_type -> helion.Ack
	9,  // 22: helion.CoordinatorService.StreamLogs:output_type -> helion.Ack
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_coordinator_proto_init() }
func file_coordinator_proto_init() {
	if File_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_proto_depIdxs,
		EnumInfos:         file_coordinator_proto_enumTypes,
		MessageInfos:      file_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_proto = out.File
	file_coordinator_proto_goTypes = nil
	file_coordinator_proto_depIdxs = nil
}
