// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourceLimits constrains a job's CPU and memory usage via cgroup v2 (Rust runtime).
// Zero values mean "no limit".
type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryBytes   uint64                 `protobuf:"varint,1,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`   // maximum resident memory in bytes
	CpuQuotaUs    uint64                 `protobuf:"varint,2,opt,name=cpu_quota_us,json=cpuQuotaUs,proto3" json:"cpu_quota_us,omitempty"`    // CPU quota per period in microseconds
	CpuPeriodUs   uint64                 `protobuf:"varint,3,opt,name=cpu_period_us,json=cpuPeriodUs,proto3" json:"cpu_period_us,omitempty"` // accounting period in microseconds (default 100000)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceLimits) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceLimits) GetCpuQuotaUs() uint64 {
	if x != nil {
		return x.CpuQuotaUs
	}
	return 0
}

func (x *ResourceLimits) GetCpuPeriodUs() uint64 {
	if x != nil {
		return x.CpuPeriodUs
	}
	return 0
}

// ArtifactBinding is an artifact-store object attached to a job, either as
// an input (downloaded before the command runs) or as an output (uploaded
// after the command exits 0). See internal/artifacts for URI semantics.
type ArtifactBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical name, surfaced to the job as HELION_INPUT_<NAME> or
	// HELION_OUTPUT_<NAME>. Must be a valid shell identifier ([A-Z_][A-Z0-9_]*).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Artifact URI. For inputs: where the node pulls from.
	// For outputs: set by the node after upload and recorded in the
	// terminal event payload — callers leave it empty on submit.
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	// Path relative to the job's working directory. Must stay inside
	// working_dir; absolute paths and ".." segments are rejected.
	LocalPath string `protobuf:"bytes,3,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	// Expected SHA-256 (lower-hex). Populated only on inputs whose URI
	// was resolved from an upstream's ResolvedOutput — the coordinator
	// knows the digest at resolve time. Empty on plain-URI inputs where
	// no digest has been committed. When present, the node's stager
	// verifies the download against this digest and refuses the job
	// if the bytes don't match.
	Sha256        string `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactBinding) Reset() {
	*x = ArtifactBinding{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactBinding) ProtoMessage() {}

func (x *ArtifactBinding) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactBinding.ProtoReflect.Descriptor instead.
func (*ArtifactBinding) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactBinding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactBinding) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ArtifactBinding) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *ArtifactBinding) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type DispatchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int64                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Limits         *ResourceLimits        `protobuf:"bytes,6,opt,name=limits,proto3" json:"limits,omitempty"`
	// Step 2 — ML pipeline fields.
	WorkingDir    string             `protobuf:"bytes,7,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`                                                                                  // empty = per-job temp dir
	Inputs        []*ArtifactBinding `protobuf:"bytes,8,rep,name=inputs,proto3" json:"inputs,omitempty"`                                                                                                            // staged before run
	Outputs       []*ArtifactBinding `protobuf:"bytes,9,rep,name=outputs,proto3" json:"outputs,omitempty"`                                                                                                          // uploaded after success
	NodeSelector  map[string]string  `protobuf:"bytes,10,rep,name=node_selector,json=nodeSelector,proto3" json:"node_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // advisory; enforced by coordinator scheduler
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *DispatchRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DispatchRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *DispatchRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *DispatchRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *DispatchRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *DispatchRequest) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *DispatchRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *DispatchRequest) GetInputs() []*ArtifactBinding {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *DispatchRequest) GetOutputs() []*ArtifactBinding {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *DispatchRequest) GetNodeSelector() map[string]string {
	if x != nil {
		return x.NodeSelector
	}
	return nil
}

type DispatchAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchAck) Reset() {
	*x = DispatchAck{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchAck) ProtoMessage() {}

func (x *DispatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchAck.ProtoReflect.Descriptor instead.
func (*DispatchAck) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchAck) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DispatchAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DispatchAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type NodeMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RunningJobs   int32                  `protobuf:"varint,2,opt,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	TotalJobs     int32                  `protobuf:"varint,3,opt,name=total_jobs,json=totalJobs,proto3" json:"total_jobs,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float64                `protobuf:"fixed64,5,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *NodeMetrics) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeMetrics) GetRunningJobs() int32 {
	if x != nil {
		return x.RunningJobs
	}
	return 0
}

func (x *NodeMetrics) GetTotalJobs() int32 {
	if x != nil {
		return x.TotalJobs
	}
	return 0
}

func (x *NodeMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeMetrics) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *NodeMetrics) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\x06helion\x1a\x11coordinator.proto\"y\n" +
	"\x0eResourceLimits\x12!\n" +
	"\fmemory_bytes\x18\x01 \x01(\x04R\vmemoryBytes\x12 \n" +
	"\fcpu_quota_us\x18\x02 \x01(\x04R\n" +
	"cpuQuotaUs\x12\"\n" +
	"\rcpu_period_us\x18\x03 \x01(\x04R\vcpuPeriodUs\"n\n" +
	"\x0fArtifactBinding\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x1d\n" +
	"\n" +
	"local_path\x18\x03 \x01(\tR\tlocalPath\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\"\xb1\x04\n" +
	"\x0fDispatchRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x122\n" +
	"\x03env\x18\x04 \x03(\v2 .helion.DispatchRequest.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x03R\x0etimeoutSeconds\x12.\n" +
	"\x06limits\x18\x06 \x01(\v2\x16.helion.ResourceLimitsR\x06limits\x12\x1f\n" +
	"\vworking_dir\x18\a \x01(\tR\n" +
	"workingDir\x12/\n" +
	"\x06inputs\x18\b \x03(\v2\x17.helion.ArtifactBindingR\x06inputs\x121\n" +
	"\aoutputs\x18\t \x03(\v2\x17.helion.ArtifactBindingR\aoutputs\x12N\n" +
	"\rnode_selector\x18\n" +
	" \x03(\v2).helion.DispatchRequest.NodeSelectorEntryR\fnodeSelector\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11NodeSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\vDispatchAck\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\">\n" +
	"\rCancelRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xd1\x01\n" +
	"\vNodeMetrics\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\frunning_jobs\x18\x02 \x01(\x05R\vrunningJobs\x12\x1d\n" +
	"\n" +
	"total_jobs\x18\x03 \x01(\x05R\ttotalJobs\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x05 \x01(\x01R\n" +
	"memPercent\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x03R\ruptimeSeconds\"\a\n" +
	"\x05Empty2\xa7\x01\n" +
	"\vNodeService\x128\n" +
	"\bDispatch\x12\x17.helion.DispatchRequest\x1a\x13.helion.DispatchAck\x12,\n" +
	"\x06Cancel\x12\x15.helion.CancelRequest\x1a\v.helion.Ack\x120\n" +
	"\n" +
	"GetMetrics\x12\r.helion.Empty\x1a\x13.helion.NodeMetricsB'Z%github.com/DyeAllPies/Helion-v2/protob\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_node_proto_goTypes = []any{
	(*ResourceLimits)(nil),  // 0: helion.ResourceLimits
	(*ArtifactBinding)(nil), // 1: helion.ArtifactBinding
	(*DispatchRequest)(nil), // 2: helion.DispatchRequest
	(*DispatchAck)(nil),     // 3: helion.DispatchAck
	(*CancelRequest)(nil),   // 4: helion.CancelRequest
	(*NodeMetrics)(nil),     // 5: helion.NodeMetrics
	(*Empty)(nil),           // 6: helion.Empty
	nil,                     // 7: helion.DispatchRequest.EnvEntry
	nil,                     // 8: helion.DispatchRequest.NodeSelectorEntry
	(*Ack)(nil),             // 9: helion.Ack
}
var file_node_proto_depIdxs = []int32{
	7, // 0: helion.DispatchRequest.env:type_name -> helion.DispatchRequest.EnvEntry
	0, // 1: helion.DispatchRequest.limits:type_name -> helion.ResourceLimits
	1, // 2: helion.DispatchRequest.inputs:type_name -> helion.ArtifactBinding
	1, // 3: helion.DispatchRequest.outputs:type_name -> helion.ArtifactBinding
	8, // 4: helion.DispatchRequest.node_selector:type_name -> helion.DispatchRequest.NodeSelectorEntry
	2, // 5: helion.NodeService.Dispatch:input_type -> helion.DispatchRequest
	4, // 6: helion.NodeService.Cancel:input_type -> helion.CancelRequest
	6, // 7: helion.NodeService.GetMetrics:input_type -> helion.Empty
	3, // 8: helion.NodeService.Dispatch:output_type -> helion.DispatchAck
	9, // 9: helion.NodeService.Cancel:output_type -> helion.Ack
	5, // 10: helion.NodeService.GetMetrics:output_type -> helion.NodeMetrics
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_coordinator_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
